name: Windows Rtools40

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ tbb-rtools-make ]
    paths-ignore:
      - 'doygen/**'
      - 'hooks/**'
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  rtools-build-check:
    runs-on: windows-latest
    name: R ${{ matrix.config.r }} with Rtools ${{ matrix.config.rtools }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '4.3.2', rtools: '43', path: 'C:/rtools43/x86_64-w64-mingw32.static.posix/bin;C:/rtools43/usr/bin'}
          - {os: windows-latest, r: '4.2.3', rtools: '42', path: 'C:/rtools42/x86_64-w64-mingw32.static.posix/bin;C:/rtools42/usr/bin'}
          - {os: windows-latest, r: '4.1.3', rtools: '40', path: 'C:/rtools40/mingw64/bin;C:/rtools40/usr/bin'}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
        rtools-version: ${{ matrix.config.rtools }}

    - name: Set path for Rtools${{ matrix.config.rtools }}
      run: echo "${{ matrix.config.path }}" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Build Math libs
      shell: powershell
      run: |
        Add-Content make\local "O=1`n"
        make -f make/standalone math-libs -j2
